-- Generated by psc-make version 0.6.8
module Network.HTTP.Method where
import Prelude ()
import Prim ()
import Prelude ()
data Method = DELETE  | GET  | HEAD  | OPTIONS  | PATCH  | POST  | PUT  | MOVE  | COPY  | CustomMethod Prim.String
foreign import methodToString :: Network.HTTP.Method.Method -> Prim.String
foreign import instance eqMethod :: Prelude.Eq Network.HTTP.Method.Method
foreign import instance showMethod :: Prelude.Show Network.HTTP.Method.Method
