-- Generated by psc-make version 0.6.8
module DOM.XHR where
import Prim ()
import Prelude ()
--  | An `XMLHttpRequest` object instance.
--  | A `FormData` object instance.
--  | A `ProgressEvent` object instance.
foreign import data ProgressEvent :: *
foreign import data FormData :: *
foreign import data XMLHttpRequest :: *
