-- Generated by psc-make version 0.6.8
module Network.HTTP.ResponseHeader where
import Prelude ()
import Prim ()
import Prelude ()
data ResponseHeader
foreign import responseHeader :: Prim.String -> Prim.String -> Network.HTTP.ResponseHeader.ResponseHeader
foreign import instance eqResponseHeader :: Prelude.Eq Network.HTTP.ResponseHeader.ResponseHeader
foreign import instance showResponseHeader :: Prelude.Show Network.HTTP.ResponseHeader.ResponseHeader
