-- Generated by psc-make version 0.6.8
module Main where
import Debug.Trace ()
import Prim ()
import Prelude ()
import Debug.Trace ()
foreign import main :: forall t2. Control.Monad.Eff.Eff (trace :: Debug.Trace.Trace | t2) Prelude.Unit
