-- Generated by psc-make version 0.6.8
module DOM.File where
import Prim ()
import Prelude ()
--  | A `File` object instance.
--  | A `FileList` object instance.
--  | A `FileReader` object instance.
--  | A `Blob` object instance.
foreign import data Blob :: *
foreign import data FileReader :: *
foreign import data FileList :: *
foreign import data File :: *
