-- Generated by psc-make version 0.6.8
module Data.DOM.Simple.Unsafe.Utils where
import Data.DOM.Simple.Unsafe.Utils ()
import Prim ()
import Prelude ()
import Data.Maybe ()
foreign import showImpl :: forall a. a -> Prim.String
foreign import ensure :: forall t21. t21 -> Data.Maybe.Maybe t21
foreign import ensure3 :: forall a. Data.Maybe.Maybe a -> (a -> Data.Maybe.Maybe a) -> a -> Data.Maybe.Maybe a
