-- Generated by psc-make version 0.6.8
module Network.HTTP.StatusCode where
import Prelude ()
import Prim ()
import Prelude ()
import Data.Int ()
newtype StatusCode = StatusCode Data.Int.Int
foreign import instance eqStatusCode :: Prelude.Eq Network.HTTP.StatusCode.StatusCode
foreign import instance showStatusCode :: Prelude.Show Network.HTTP.StatusCode.StatusCode
