-- Generated by psc-make version 0.6.8
module Data.Void where
import Prelude ()
import Data.Void ()
import Data.Functor.Contravariant ()
import Prim ()
import Prelude ()
import Data.Functor.Contravariant ()
newtype Void = Void Data.Void.Void
foreign import absurd :: forall a. Data.Void.Void -> a
foreign import coerce :: forall f a b. (Data.Functor.Contravariant.Contravariant f, Prelude.Functor f) => f a -> f b
