-- Generated by psc-make version 0.6.8
module Network.HTTP.MimeType where
import Prelude ()
import Prim ()
import Prelude ()
newtype MimeType = MimeType Prim.String
foreign import mimeTypeToString :: Network.HTTP.MimeType.MimeType -> Prim.String
foreign import instance eqMimeType :: Prelude.Eq Network.HTTP.MimeType.MimeType
foreign import instance showMimeType :: Prelude.Show Network.HTTP.MimeType.MimeType
