-- Generated by psc-make version 0.6.8
module Data.DOM.Simple.Types where
import Prim ()
import Prelude ()
import Control.Monad.Eff ()
foreign import data Timeout :: *
foreign import data JavascriptContext :: *
foreign import data DOMLocation :: *
foreign import data DOMEvent :: *
foreign import data DOMNavigator :: *
foreign import data XMLHttpRequest :: *
foreign import data HTMLWindow :: *
foreign import data HTMLDocument :: *
foreign import data HTMLElement :: *
