-- Generated by psc-make version 0.6.8
module Data.Foreign.Keys where
import Data.Foreign ()
import Prelude ()
import Data.Foreign.Keys ()
import Prim ()
import Prelude ()
import Data.Either ()
import Data.Foreign ()
import Data.Function ()
--  | Get an array of the properties defined on a foreign value
foreign import keys :: Data.Foreign.Foreign -> Data.Foreign.F [Prim.String]
